name: Django CVE Rooster CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unittest:
    name: Check Code Format And Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: x64
      - name: Install Apache Development Package
        run: sudo apt-get update && sudo apt-get install -y apache2-dev
      - name: Install Python Packages
        run: pip3 install -r requirements.txt
      - name: Start Docker Compose
        run: docker-compose up -d
      - name: Check Code Format
        run: tox -e flake8
      - name: Unit Test
        run: tox -e testapp
