name: Django CVE Rooster CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unittest:
    name: Check Code Format And Unit Test
    strategy:
      matrix:
        # python-version: [3.7, 3.8, 3.9]
        python-version: [3.7]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Python3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Apache Development Package
        run: sudo apt-get update && sudo apt-get install -y apache2-dev
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # - name: Start Docker Compose
      #   run: docker-compose up -d
      - name: Check Code Format
        run: tox -e flake8
      - name: Unit Test
        run: tox -e testapp
